### ISSUE TITLE
io.kcache.exceptions.CacheInitializationException: Failed trying to create or validate topic my-topic

### ISSUE THREAD

**Issue by hermanjakobsen** [rayokota/kcache#163]
Hi! 

I have an application running `KCache`. The application consists of several threads that each polls from a topic and then saves the records to their own kcache. Periodically, each thread reads a set of  the stored record and analyze them. The application is deployed on OpenShift as a container and runs fine for a good period of time.

However, after about twelve hours of runtime, the application crashes with the following error message: 
```
Exception in thread "main" io.kcache.exceptions.CacheInitializationException: Failed trying to create or validate my-topic-kcache
	at io.kcache.KafkaCache.createOrVerifyTopic(KafkaCache.java:350)
	at io.kcache.KafkaCache.init(KafkaCache.java:267)
	at utils.Cache.<init>(Cache.kt:40)
	at consumers.MyThread.<init>(MyThread.kt:39)
	at ApplicationKt.module(Application.kt:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at io.ktor.server.engine.internal.CallableUtilsKt.callFunctionWithInjection(CallableUtils.kt:119)
	at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:36)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:30)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:312)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:143)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:174)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:26)
	at ApplicationKt.main(Application.kt:33)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1632808693387, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:104)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
	at io.kcache.KafkaCache.createOrVerifyTopic(KafkaCache.java:336)
	... 29 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1632808693387, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited. Call: listTopics
{"@timestamp":"2021-09-28T07:57:57.759+02:00","@version":"1","message":"Thread kafka-cache-reader-thread-thread1-kcache exiting with uncaught exception: ","logger_name":"io.kcache.utils.ShutdownableThread","thread_name":"kafka-cache-reader-thread-thread1-kcache","level":"ERROR","level_value":40000,"stack_trace":"java.lang.OutOfMemoryError: Java heap space\n"}
Exception in thread "thread1" java.lang.OutOfMemoryError: Java heap space
Exception in thread "kafka-cache-reader-thread-thread1-kcache" java.lang.OutOfMemoryError: Java heap space
```
The caches have the following configuration: 
```
val cacheProps = Properties()
            cacheProps[KafkaCacheConfig.KAFKACACHE_BOOTSTRAP_SERVERS_CONFIG] =
                appConfig.propertyOrNull("kafka.bootstrapServers")?.getString()
            cacheProps[KafkaCacheConfig.KAFKACACHE_GROUP_ID_CONFIG] =
                appConfig.propertyOrNull("kafka.consumerGroupIdPrefix")?.getString() + "-$name-kcache"
            cacheProps[KafkaCacheConfig.KAFKACACHE_TOPIC_CONFIG] =
                appConfig.propertyOrNull("applicationId")?.getString() + "$name-kcache"
            cacheProps[KafkaCacheConfig.KAFKACACHE_SECURITY_PROTOCOL_CONFIG] =
                appConfig.propertyOrNull("kafka.securityProtocol")?.getString()
```
Has anyone experienced anything similar, or have a solution to this problem?

**Comment by rayokota** [comment]
It appears your application is running out of memory.  You can try increasing your JVM heap size, or using a `CaffeineCache` to back your `KafkaCache`, which will evict older entries.

**Comment by hermanjakobsen** [comment]
So there is a limited storage space on the `KCache` topic? I thought one of the properties of Kafka is the ability to store large amounts of data? For my application, the topic will at maximum contain 60 000 avro records before I manually delete the oldest records. Should not the cache be able to handle this amount of records?

**Comment by hermanjakobsen** [comment]
Taking a heap memory dump of my application, I can see that `KCache` implements an `InMemoryCache` local cache where all the records are stored after polling. 

Unfortunately, this makes me a little confused on how kafka and its topics are used? I thought that the topic worked as a cache and my application extracted records from that topic? Instead, it looks like all the records are stored locally? However, the `KCache` stores the data persistently , as my application have access to all the records after restart. How is that possible if it is only stored in the `localCache`? 

I would greatly appreciate if you could give an overview of how `KCache` works and how the different components interacts! :) 

Thank you for your help!

**Comment by rayokota** [comment]
Please see the following blogs:

https://yokota.blog/2018/11/19/kcache-an-in-memory-cache-backed-by-kafka/

https://yokota.blog/2020/09/30/using-kcache-with-a-persistent-cache/
