### ISSUE TITLE
Connection to node failed authentication due to: Failed to process post-handshake messages

### ISSUE THREAD

**Issue by hermanjakobsen** [rayokota/kcache#173]
Hi! 

I am a fan of KCache, and have lately been using it quite extensively! Great work! 

However, my application occasionally outputs some Kafka related error messages. More precisely, the most common error messsage is
```
Connection to node failed authentication due to: Failed to process post-handshake messages
```
with the following stack trace
```
io.kcache.exceptions.CacheTimeoutException: Put operation timed out while waiting for an ack from Kafka
	at io.kcache.KafkaCache.put(KafkaCache.java:533)
	at io.kcache.KafkaCache.put(KafkaCache.java:490)
	at Cache.insert(Cache.kt:50)
	at.Cache.insert(Cache.kt:54)
	at ConsumerThread.addToCache(ConsumerThread.kt:56)
	at ConsumerThread.addToCache$default(ConsumerThread.kt:55)
	at.ConsumerThread.run(ConsumerThread.kt:35)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting for 60000 ms.
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:78)
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:30)
	at io.kcache.KafkaCache.put(KafkaCache.java:522)
	... 6 common frames omitted
```
To clarify, for my application I have implemented a wrapper class `Cache`, containing simple logic, around the KCache .

Do you have any tips on how to overcome/solve these errors?

**Comment by rayokota** [comment]
One option is to set `kafkacache.timeout.ms` to a higher value, such as `300000`.

**Comment by hermanjakobsen** [comment]
This is in my opinion a somewhat poor solution. The application will continue to spew out 
```
ERROR: Connection to node failed authentication due to: Failed to process post-handshake messages
```
while waiting for the `kafkacache.timeout.ms`. 

Is there a way to solve the `Failed to process post-handshake messages` error?
